import type { RealEstateAgent } from './types';

export const demoAgents: RealEstateAgent[] = [
  {
    id: 'agent-prime-gate',
    slug: 'prime-gate-realty',
    type: 'company',
    name: 'Prime Gate Realty',
    logoUrl: '/assets/developers/prime-urban.svg',
    locationId: 'loc-new-cairo',
    locationLabel: 'القاهرة الجديدة',
    serviceAreaLabels: ['القاهرة الجديدة', 'التجمع الخامس'],
    description: 'شركة وساطة تركز على الوحدات السكنية في شرق القاهرة.',
    memberSinceYear: 2016,
    partnershipYears: 9,
    listingCount: 15,
    customerCount: 1840,
    verified: true,
    phone: '+201000001101',
    whatsappPhone: '+201000001101',
    propertySellerId: 'seller-prime-gate',
  },
  {
    id: 'agent-nile-keys',
    slug: 'nile-keys-properties',
    type: 'company',
    name: 'Nile Keys Properties',
    logoUrl: '/assets/developers/nile-horizon.svg',
    locationId: 'loc-fifth-settlement',
    locationLabel: 'التجمع الخامس',
    serviceAreaLabels: ['التجمع الخامس', 'القاهرة الجديدة'],
    memberSinceYear: 2018,
    partnershipYears: 7,
    listingCount: 3,
    customerCount: 960,
    verified: true,
    phone: '+201000001102',
    whatsappPhone: '+201000001102',
    propertySellerId: 'seller-nile-keys',
  },
  {
    id: 'agent-urban-point',
    slug: 'urban-point-realty',
    type: 'company',
    name: 'Urban Point Realty',
    logoUrl: '/assets/developers/oasis-homes.svg',
    locationId: 'loc-nasr-city',
    locationLabel: 'مدينة نصر',
    serviceAreaLabels: ['مدينة نصر', 'القاهرة'],
    memberSinceYear: 2019,
    partnershipYears: 6,
    listingCount: 4,
    customerCount: 720,
    verified: true,
    phone: '+201000001103',
    whatsappPhone: '+201000001103',
    propertySellerId: 'seller-urban-point',
  },
  {
    id: 'agent-bayt-asima',
    slug: 'bayt-al-asima',
    type: 'company',
    name: 'بيت العاصمة العقارية',
    logoUrl: '/assets/developers/delta-living.svg',
    locationId: 'loc-greater-cairo',
    locationLabel: 'القاهرة الكبرى',
    serviceAreaLabels: ['القاهرة الكبرى', 'مدينة نصر'],
    memberSinceYear: 2014,
    partnershipYears: 11,
    listingCount: 4,
    customerCount: 1320,
    verified: true,
    phone: '+201000001104',
    whatsappPhone: '+201000001104',
    propertySellerId: 'seller-bayt-asima',
  },
  {
    id: 'agent-miftah',
    slug: 'miftah-al-qahira',
    type: 'company',
    name: 'مفتاح القاهرة',
    logoUrl: '/assets/developers/coastal-vista.svg',
    locationId: 'loc-maadi',
    locationLabel: 'المعادي',
    serviceAreaLabels: ['المعادي', 'القاهرة'],
    memberSinceYear: 2020,
    partnershipYears: 5,
    listingCount: 3,
    customerCount: 410,
    verified: false,
    phone: '+201000001105',
    whatsappPhone: '+201000001105',
    propertySellerId: 'seller-miftah',
  },
  {
    id: 'agent-delta-view',
    slug: 'delta-view-estates',
    type: 'company',
    name: 'Delta View Estates',
    logoUrl: '/assets/developers/prime-urban.svg',
    locationId: 'loc-6th-october',
    locationLabel: '6 أكتوبر',
    serviceAreaLabels: ['6 أكتوبر', 'الشيخ زايد'],
    memberSinceYear: 2017,
    partnershipYears: 8,
    listingCount: 3,
    customerCount: 640,
    verified: true,
    phone: '+201000001106',
    whatsappPhone: '+201000001106',
    propertySellerId: 'seller-delta-view',
  },
  {
    id: 'agent-harbor-line',
    slug: 'harbor-line-realty',
    type: 'company',
    name: 'Harbor Line Realty',
    logoUrl: '/assets/developers/nile-horizon.svg',
    locationId: 'loc-alexandria',
    locationLabel: 'الإسكندرية',
    serviceAreaLabels: ['الإسكندرية', 'سموحة'],
    memberSinceYear: 2015,
    partnershipYears: 10,
    listingCount: 2,
    customerCount: 880,
    verified: true,
    phone: '+201000001107',
    whatsappPhone: '+201000001107',
    propertySellerId: 'seller-harbor-line',
  },
  {
    id: 'agent-huda',
    slug: 'huda-mansour',
    type: 'broker',
    name: 'هدى منصور',
    avatarUrl: '/assets/marketing-services/avatars/a1.webp',
    locationId: 'loc-new-cairo',
    locationLabel: 'القاهرة الجديدة',
    serviceAreaLabels: ['القاهرة الجديدة', 'التجمع الخامس'],
    memberSinceYear: 2019,
    partnershipYears: 6,
    listingCount: 2,
    customerCount: 210,
    verified: true,
    phone: '+201000001201',
    whatsappPhone: '+201000001201',
    propertySellerId: 'seller-huda-mansour',
  },
  {
    id: 'agent-karim',
    slug: 'karim-el-shafie',
    type: 'broker',
    name: 'كريم الشافعي',
    avatarUrl: '/assets/marketing-services/avatars/a2.webp',
    locationId: 'loc-fifth-settlement',
    locationLabel: 'التجمع الخامس',
    serviceAreaLabels: ['التجمع الخامس'],
    memberSinceYear: 2021,
    partnershipYears: 4,
    listingCount: 2,
    customerCount: 156,
    verified: true,
    phone: '+201000001202',
    whatsappPhone: '+201000001202',
    propertySellerId: 'seller-karim-shafie',
  },
  {
    id: 'agent-nora',
    slug: 'nora-abdel-fattah',
    type: 'broker',
    name: 'نورا عبد الفتاح',
    avatarUrl: '/assets/marketing-services/avatars/a3.webp',
    locationId: 'loc-sheikh-zayed',
    locationLabel: 'الشيخ زايد',
    serviceAreaLabels: ['الشيخ زايد', '6 أكتوبر'],
    memberSinceYear: 2018,
    partnershipYears: 7,
    listingCount: 2,
    customerCount: 298,
    verified: true,
    phone: '+201000001203',
    whatsappPhone: '+201000001203',
    propertySellerId: 'seller-nora',
  },
  {
    id: 'agent-samer',
    slug: 'samer-tawfik',
    type: 'broker',
    name: 'سامر توفيق',
    avatarUrl: '/assets/marketing-services/avatars/a1.webp',
    locationId: 'loc-nasr-city',
    locationLabel: 'مدينة نصر',
    serviceAreaLabels: ['مدينة نصر'],
    memberSinceYear: 2022,
    partnershipYears: 3,
    listingCount: 0,
    customerCount: 64,
    verified: false,
    phone: '+201000001204',
    whatsappPhone: '+201000001204',
  },
  {
    id: 'agent-layla',
    slug: 'layla-hassan',
    type: 'broker',
    name: 'ليلى حسن',
    avatarUrl: '/assets/marketing-services/avatars/a2.webp',
    locationId: 'loc-maadi',
    locationLabel: 'المعادي',
    serviceAreaLabels: ['المعادي'],
    memberSinceYear: 2020,
    partnershipYears: 5,
    listingCount: 0,
    customerCount: 118,
    verified: true,
    phone: '+201000001205',
    whatsappPhone: '+201000001205',
  },
  {
    id: 'agent-youssef',
    slug: 'youssef-adel',
    type: 'broker',
    name: 'يوسف عادل',
    avatarUrl: '/assets/marketing-services/avatars/a3.webp',
    locationId: 'loc-alexandria',
    locationLabel: 'الإسكندرية',
    serviceAreaLabels: ['الإسكندرية'],
    memberSinceYear: 2017,
    partnershipYears: 8,
    listingCount: 0,
    customerCount: 340,
    verified: true,
    phone: '+201000001206',
    whatsappPhone: '+201000001206',
  },
  {
    id: 'agent-adam',
    slug: 'adam-fouad',
    type: 'broker',
    name: 'آدم فؤاد',
    avatarUrl: '/assets/marketing-services/avatars/a1.webp',
    locationId: 'loc-north-coast',
    locationLabel: 'الساحل الشمالي',
    serviceAreaLabels: ['الساحل الشمالي'],
    memberSinceYear: 2023,
    partnershipYears: 2,
    listingCount: 0,
    customerCount: 28,
    verified: false,
    phone: '+201000001207',
    whatsappPhone: '+201000001207',
  },
];
