import type { ListingDraftStep } from './types';
import type { FinishingType } from '@/types';

export const LISTING_STEPS: {
  id: ListingDraftStep;
  label: string;
}[] = [
  { id: 'basic', label: 'المعلومات الأساسية' },
  { id: 'details', label: 'تفاصيل العقار والمزايا' },
  { id: 'price', label: 'سعر العقار' },
  { id: 'description', label: 'وصف العقار' },
  { id: 'contact', label: 'بيانات التواصل' },
  { id: 'media', label: 'الفيديوهات والصور' },
  { id: 'preview', label: 'معاينة الإعلان' },
  { id: 'publish', label: 'إرسال للمراجعة' },
];

export const listingCopy = {
  continue: 'متابعة',
  chooseSection: 'اختر القسم',
  sale: 'للبيع',
  rent: 'للإيجار',
  propertyType: 'نوع العقار',
  propertyTypePlaceholder: 'اختر نوع العقار',
  location: 'الموقع',
  locationPlaceholder: 'ابحث',
  mapTitle: 'موقع العقار على الخريطة',
  feeNotice: (amount: number) => `سعر الإعلان لهذا الموقع ${amount.toLocaleString('en-US')} ج.م`,
  area: 'المساحة (بالمتر)',
  bedrooms: 'عدد الغرف',
  bathrooms: 'عدد الحمامات',
  floor: 'الدور',
  year: 'سنة البناء أو التسليم',
  views: 'الإطلالات',
  finishing: 'نوع التشطيب',
  furnished: 'مفروش؟',
  legalStatus: 'الحالة القانونية',
  mortgage: 'عقارك قابل للتمويل العقاري؟',
  amenities: 'مزايا العقار',
  paymentMethod: 'طريقة الدفع',
  developer: 'من المطور',
  ownerCash: 'من المالك (نقداً)',
  ownerInstallments: 'من المالك (متبقي أقساط)',
  price: 'السعر',
  installmentTotal: 'سعر التقسيط الكلي',
  downPayment: 'المقدم',
  installmentDuration: 'مدة التقسيط',
  years: 'سنوات',
  months: 'شهور',
  monthlyInstallment: (amount: number) =>
    `القسط الشهري ${amount.toLocaleString('en-US')} ج.م/ شهر`,
  downPaymentPercent: (pct: number) => `نسبة المقدم: ${pct}%`,
  contractPrice: 'سعر العقد',
  overPrice: 'الزيادة المطلوبة - Over Price (اختياري)',
  maintenance: 'وديعة الصيانة (اختياري)',
  totalPaid: 'إجمالي المبلغ المدفوع',
  remainingPeriod: 'مدة التقسيط المتبقية',
  rentPrice: 'سعر الإيجار',
  descriptionTitle: 'وصف العقار',
  contactTitle: 'بيانات التواصل',
  contactAccountMode: 'استخدام بيانات الحساب',
  contactCustomMode: 'بيانات تواصل مختلفة',
  contactName: 'اسم جهة التواصل',
  contactType: 'نوع جهة التواصل',
  contactTypeOwner: 'مالك',
  contactTypeAgent: 'وسيط',
  contactTypeCompany: 'شركة',
  contactPhone: 'رقم الهاتف',
  contactWhatsapp: 'رقم واتساب',
  contactEmail: 'البريد الإلكتروني (اختياري)',
  contactReviewTitle: 'بيانات التواصل',
  contactEdit: 'تعديل',
  arTab: 'عربي',
  enTab: 'English',
  listingNameAr: 'اسم الإعلان',
  listingDescAr: 'وصف العقار',
  listingAddressAr: 'عنوان العقار',
  listingNameEn: 'Listing Name',
  listingDescEn: 'Listing Description',
  listingAddressEn: 'Property Address',
  autoGenerate: 'أنشئ تلقائي',
  autoGenerateEn: 'Auto Generate',
  mediaTitle: 'الفيديوهات والصور',
  photos: 'صور العقار',
  addPhotos: 'أضف الصور هنا',
  maxSize: 'أكبر حجم: 30 ميجابايت',
  videoUrl: 'رابط الفيديو (اختياري)',
  videoPlaceholder: 'أضف رابط الفيديو يوتيوب',
  publishTitle: 'إرسال للمراجعة',
  previewTitle: 'معاينة الإعلان',
  previewContinue: 'متابعة إلى الإرسال',
  previewSubmit: 'إرسال للمراجعة',
  previewEdit: 'تعديل',
  previewMissingMedia: 'لم تُضف صور بعد.',
  previewMissingLocation: 'لم يُحدد الموقع بعد.',
  previewMissingContact: 'بيانات التواصل غير مكتملة.',
  previewMissingFeatures: 'لم تُختر مزايا بعد.',
  listingFeeLabel: 'تكلفة الإعلان',
  payNow: 'ادفع الآن',
  checkoutPaymentTitle: 'إتمام الدفع',
  checkoutSummaryTitle: 'ملخص الباقة',
  addCard: 'اضف بطاقة جديدة',
  totalDue: 'إجمالي المستحق',
  payAndPublish: 'ادفع وأرسل للمراجعة',
  tipsTitle: 'نصائح لإعلان أفضل',
  egp: 'جنيه مصري',
  completionTitle: 'اكتمال بيانات الإعلان',
  completionReady: 'بيانات الإعلان مكتملة ويمكن اختيار الباقة.',
  completionIncomplete: 'أكمل الحقول التالية قبل اختيار الباقة أو الإرسال.',
  plansTitle: 'اختر باقة النشر',
  selectPlan: 'اختيار هذه الباقة',
  planDuration: (days: number) => `المدة: ${days} يوم`,
  planFree: 'مجانية',
  submittedTitle: 'تم إرسال العقار للمراجعة',
  submittedBody:
    'إعلانك الآن في انتظار مراجعة الإدارة. لن يظهر في السوق قبل الموافقة.',
  viewMyProperties: 'عرض عقاراتي',
  viewPropertyStatus: 'عرض حالة العقار',
  waitingReviewTitle: 'الإعلان قيد المراجعة',
  waitingReviewBody: 'تم استلام إعلانك وهو الآن في انتظار موافقة الإدارة.',
  publishedTitle: 'الإعلان منشور',
  publishedBody: 'تمت الموافقة على إعلانك وهو ظاهر في السوق.',
  rejectedTitle: 'تم رفض العقار',
  rejectedBody:
    'تم رفض العقار. يرجى مراجعة بيانات العقار وتعديلها ثم إعادة الإرسال.',
  resubmit: 'إعادة الإرسال للمراجعة',
  editListing: 'تعديل الإعلان',
  paySubscription: 'إتمام الدفع',
  paymentSuccessTitle: 'تم الدفع بنجاح',
  paymentSuccessBody: 'تم إرسال العقار للمراجعة بعد إتمام الدفع.',
  pendingPaymentTitle: 'بانتظار الدفع',
  pendingPaymentBody: 'اختر باقة مدفوعة. أكمل الدفع لإرسال الإعلان للمراجعة.',
} as const;

export const completionFieldLabels: Record<string, string> = {
  title: 'عنوان الإعلان',
  propertyTypeId: 'نوع العقار',
  transactionTypeId: 'نوع العملية (بيع / إيجار)',
  areaId: 'المنطقة',
  price: 'السعر',
  images: 'صورة واحدةً على الأقل',
};

export const listingFinishingOptions: {
  value: FinishingType;
  label: string;
}[] = [
  { value: 'super_lux', label: 'سوبر لوكس' },
  { value: 'lux', label: 'لوكس' },
  { value: 'finished', label: 'تشطيب كامل' },
  { value: 'semi_finished', label: 'نصف تشطيب' },
  { value: 'unfinished', label: 'بدون تشطيب' },
];

/** Legacy demo assets for unfinished publish/checkout cookie shell only. */
export const DEMO_PROPERTY_IMAGES = [
  '/assets/properties/property-01.webp',
  '/assets/properties/property-02.webp',
  '/assets/properties/property-03.webp',
  '/assets/properties/property-04.webp',
  '/assets/properties/property-05.webp',
] as const;
