import {
  BadgeDollarSign,
  Bell,
  Building2,
  CalendarDays,
  ChartNoAxesColumnIncreasing,
  ChevronDown,
  CircleDollarSign,
  CreditCard,
  Crown,
  FileSearch,
  Headphones,
  Heart,
  Languages,
  Lightbulb,
  ListChecks,
  LogOut,
  MapPin,
  MessagesSquare,
  NotebookPen,
  Pencil,
  Plus,
  RotateCcw,
  Search,
  Settings,
  ShoppingBag,
  SlidersHorizontal,
  StickyNote,
  UserRound,
  UserRoundCheck,
  Users,
  Wallet,
  X,
  type LucideIcon,
} from 'lucide-react';

export const appIcons = {
  sale: BadgeDollarSign,
  rent: CircleDollarSign,
  compounds: Building2,
  know: MapPin,
  addProperty: Plus,
  account: UserRound,
  support: Headphones,
  language: Languages,
  location: MapPin,
  filter: SlidersHorizontal,
  close: X,
  reset: RotateCcw,
  search: Search,
  chevronDown: ChevronDown,
  section: ShoppingBag,
  valuation: BadgeDollarSign,
  propertyPrices: CircleDollarSign,
  askNeighborhood: MessagesSquare,
  knowMore: MapPin,
  compoundReview: Building2,
  agents: UserRoundCheck,
  exhibitions: CalendarDays,
  propertyIndex: ChartNoAxesColumnIncreasing,
  advice: Lightbulb,
  research: FileSearch,
  // Account + authenticated menu
  favorites: Heart,
  notes: StickyNote,
  notifications: Bell,
  alerts: ListChecks,
  accountProfile: UserRound,
  accountSecurity: Settings,
  accountCards: CreditCard,
  accountWallet: Wallet,
  accountSubscription: Crown,
  accountContacts: Users,
  edit: Pencil,
  logout: LogOut,
  myProperties: Building2,
  credits: Wallet,
  recharge: CreditCard,
  activities: NotebookPen,
} as const;

export type AppIconName = keyof typeof appIcons;

export function getAppIcon(name: AppIconName): LucideIcon {
  return appIcons[name];
}

export const ICON_SIZE_NAV = 18;
export const ICON_SIZE_UI = 16;
