export const uiLabels = {
  brandTagline: 'منصة عقارية عربية',
  addListing: 'أعلن عن عقارك',
  login: 'تسجيل الدخول',
  favorites: 'المفضلة',
  languageSwitch: 'EN',
  languageSwitchAria: 'التبديل إلى الإنجليزية (قريبًا)',
  openMenu: 'فتح القائمة',
  closeMenu: 'إغلاق القائمة',
  primaryNav: 'التنقل الرئيسي',
  mobileNav: 'قائمة التنقل',
  searchNav: 'بحث عن العقارات',
  buy: 'للبيع',
  rent: 'للإيجار',
  compounds: 'كمبوندات',
  propertyType: 'نوع العقار',
  propertyTypePlaceholder: 'اختر نوع العقار',
  location: 'الموقع',
  locationPlaceholder: 'اكتب اسم المدينة أو المنطقة أو الكمبوند',
  locationClear: 'مسح الموقع',
  minPrice: 'السعر من',
  maxPrice: 'السعر إلى',
  pricePlaceholder: 'مثال: 3000000',
  searchSubmit: 'بحث',
  advancedFilters: 'خيارات بحث',
  advancedFiltersTitle: 'خيارات بحث أخرى',
  resetFilters: 'إعادة ضبط',
  filterSection: 'القسم',
  filterArea: 'منطقة',
  filterAreaPlaceholder: 'المدينة أو الحي أو اسم الشارع',
  filterPropertyType: 'نوع العقار',
  filterPayment: 'طريقة الدفع',
  filterDownPayment: 'مقدم',
  filterDownPaymentPlaceholder: 'بحث بالمقدم',
  filterInstallmentYears: 'سنوات التقسيط',
  filterInstallmentYearsPlaceholder: 'بحث بسنوات التقسيط',
  filterPrice: 'السعر (جنيه مصري)',
  filterAreaRange: 'المساحة',
  filterView: 'الإطلالة',
  filterKeyword: 'بحث بالكلمة',
  filterKeywordPlaceholder: 'جراج، حمام سباحة، روف، إلخ...',
  currencyFull: 'جنيه مصري',
  proBadge: 'Pro',
  insideCompoundOnly: 'عرض العقارات داخل كمبوند فقط',
  directOwnerOnly: 'عرض العقارات من المالك مباشرة',
  hasVideoOnly: 'عرض العقارات التي تحتوي على فيديو',
  aiRecommended: 'نتائج مخصصة لك بالذكاء الاصطناعي',
  languageCode: 'AR',
  support: 'الدعم',

  allPropertyTypes: 'كل الأنواع',
  noLocations: 'لا توجد نتائج مطابقة',
  currencySuffix: 'ج.م',
  announcement:
    'عروض وخصومات حصرية على وحدات مختارة — تصفح أحدث الفرص العقارية الآن',
  closeAnnouncement: 'إغلاق الشريط الإعلاني',
  heroTitle: 'ابدأ البحث عن بيت أحلامك',
  heroStatus: '+٨٬٠٠٠ إعلان متاح الآن',
  latestCompounds: 'أحدث الكمبوندات',
  viewAll: 'عرض الكل',
  startingFrom: 'تبدأ من',
  viewCompound: 'عرض التفاصيل',
  newBadge: 'طرح جديد',
  importantAreas: 'أهم المناطق',
  knowHeading: 'أعرف',
  learnMore: 'تفاصيل أكثر',
  carouselPrev: 'الشريحة السابقة',
  carouselNext: 'الشريحة التالية',
  downloadAppHeading: 'حمّل التطبيق',
  scanForApp: 'امسح للتطبيق',
  premiumMessage: 'استمتع بمزايا غير محدودة مع اشتراك برو',
  premiumCta: 'اشترك الآن',
  addPropertyTitle: 'أعلن عن عقارك',
  addPropertyDescription:
    'انشر عقارك مجانًا ووصل إلى آلاف الباحثين عن الشراء والإيجار شهريًا.',
  addPropertyPrimary: 'أضف عقارك الآن',
  addPropertySecondary: 'تعرّف على المزايا',
  aiTitlePrefix: 'اعرف السعر التقريبي لعقارك',
  aiTitleAccent: 'بالذكاء الاصطناعي',
  aiDescription: 'قدّر قيمة وحدتك خلال دقائق بمساعدة أدوات التقييم الذكية.',
  aiCta: 'احسب قيمة عقارك',
  appTitle: 'حمّل تطبيق عقارات مصر الآن',
  appDescription:
    'ابحث، قارن، وتواصل مع المعلنين بسهولة من هاتفك في أي وقت.',
  appUsers: '+١ مليون مستخدم',
  resultsLocationPlaceholder: 'المدينة أو الحي أو اسم الشارع',
  sortBy: 'الترتيب حسب',
  sortRecommended: 'موصى به',
  sortNewest: 'الأحدث',
  sortPriceAsc: 'السعر من الأقل للأعلى',
  sortPriceDesc: 'السعر من الأعلى للأقل',
  mapSearch: 'بحث بالخريطة',
  newBadgeShort: 'جديد',
  verifiedBadge: 'موثق',
  emptyResultsTitle: 'لا توجد نتائج مطابقة',
  emptyResultsDescription:
    'جرّب تعديل الفلاتر أو تغيير الموقع للحصول على نتائج أكثر.',
  emptyResultsReset: 'إعادة ضبط البحث',
  paginationPrev: 'السابق',
  paginationNext: 'التالي',
  aiResultsTitle: 'نتائج مخصصة بالذكاء الاصطناعي',
  aiResultsDescription:
    'الذكاء الاصطناعي يساعدك في عرض العقارات الأقرب لتفضيلاتك وسلوكك',
  listingPlaceholderTitle: 'صفحة تفاصيل العقار',
  listingPlaceholderBody: 'تفاصيل هذا الإعلان قيد التجهيز وستكون متاحة قريبًا.',
  backToResults: 'العودة لنتائج البحث',
  bedroomsShort: 'غرف',
  bathroomsShort: 'حمام',
  imageCountLabel: 'صور',
  addFavorite: 'إضافة إلى المفضلة',
  removeFavorite: 'إزالة من المفضلة',
  searchPromoTitle: 'أعلن عن عقارك الآن',
  searchPromoBody: 'وصول أوسع للمشترين والمستأجرين مع باقات إعلان مرنة.',
  searchPromoCta: 'ابدأ الإعلان',

  // Property details
  whatsapp: 'واتساب',
  call: 'اتصال',
  financingBadge: 'تقسيط',
  viewAllPhotos: 'عرض كل الصور',
  morePhotos: 'صور إضافية',
  saveAction: 'حفظ',
  noteAction: 'ملاحظة',
  shareAction: 'مشاركة',
  reportAction: 'إبلاغ',
  linkCopied: 'تم نسخ الرابط',
  detailsSectionTitle: 'تفاصيل الإعلان',
  installmentSectionTitle: 'تفاصيل التقسيط',
  installmentPrice: 'سعر التقسيط',
  downPaymentLabel: 'المقدم',
  installmentDuration: 'مدة التقسيط',
  monthlyInstallmentLabel: 'القسط الشهري',
  yearsUnit: 'سنوات',
  descriptionSectionTitle: 'وصف الإعلان',
  showMore: 'أظهر المزيد',
  showLess: 'أظهر أقل',
  amenitiesSectionTitle: 'مزايا العقار',
  travelTimeTitle: 'وقت الوصول للشقة',
  travelModeCar: 'العربية',
  travelModeWalk: 'المشي',
  travelOriginPlaceholder: 'أدخل نقطة الانطلاق',
  travelPlaceholderHint: 'أدخل موقعك لعرض تقدير وقت الوصول',
  mapSectionTitle: 'الموقع على الخريطة',
  openFullMap: 'فتح الخريطة بالكامل',
  sellerSectionTitle: 'تواصل مع المعلن',
  sellerListings: 'إعلان',
  compoundRecommendTitle: 'موصى به داخل الكمبوند',
  compoundRecommendCta: 'استكشف الكمبوند',
  statisticsSectionTitle: 'إحصائيات الإعلان',
  statSearchAppearances: 'مرات الظهور في البحث',
  statViews: 'المشاهدات',
  statFavorites: 'الإضافات للمفضلة',
  proLockedHint: 'متاح مع Pro',
  compoundRatingTitlePrefix: 'تقييم كمبوند',
  similarListingsTitle: 'إعلانات ذات صلة',
  agentsStripTitle: 'شركات ووسطاء موصى بهم',
  proBannerTitle: 'توصية Pro',
  proBannerBody:
    'احصل على تحليل أوضح لسعر الوحدة ومقارنتها بعقارات مشابهة في نفس المنطقة.',
  proBannerCta: 'جرّب Pro',
  priceInsightTitle: 'هل السعر مناسب للمنطقة؟',
  priceInsightBody:
    'راجع مؤشر الأسعار المحلي وقارن هذه الوحدة بعقارات مشابهة قبل اتخاذ القرار.',
  priceInsightCta: 'اعرف المزيد',
  showPropertyLocation: 'إظهار موقع العقار',
  viewMore: 'عرض المزيد',
  sectionNavPhotos: 'الصور',
  sectionNavDetails: 'التفاصيل',
  sectionNavAmenities: 'المزايا',
  sectionNavLocation: 'الموقع',
  sectionNavStatistics: 'الإحصائيات والتقييمات',
  detailFloor: 'الدور',
  detailDeliveryYear: 'سنة التسليم',
  detailView: 'الإطلالة',
  detailSellerType: 'نوع المعلن',
  detailReference: 'رقم الإعلان',
  detailPricePerMeter: 'سعر المتر',
  detailFinishing: 'التشطيب',
  detailGardenArea: 'مساحة الحديقة',
  detailPaymentType: 'طريقة الدفع',
  sellerTypeOwner: 'مالك',
  sellerTypeBroker: 'وسيط',
  sellerTypeAgency: 'شركة عقارية',
  sellerTypeDeveloper: 'مطوّر',
  finishingUnfinished: 'بدون تشطيب',
  finishingSemi: 'نصف تشطيب',
  finishingFinished: 'تشطيب كامل',
  finishingLux: 'لوكس',
  finishingSuperLux: 'سوبر لوكس',
  paymentCash: 'كاش',
  paymentInstallment: 'تقسيط',
  paymentCashOrInstallment: 'كاش أو تقسيط',
  forSale: 'للبيع',
  forRent: 'للإيجار',

  // Compounds directory
  compoundsDirectoryBreadcrumb: 'دليل الكمبوند',
  compoundsDirectoryTitlePrefix: 'دليل الكمبوند',
  compoundsDirectoryTitleSuffix: 'مشروع بأسعار كل الوحدات',
  compoundsFilterResults: 'تصفية النتائج',
  compoundsFilterLocations: 'الأماكن',
  compoundsFilterPropertyTypes: 'أنواع العقارات',
  compoundsFilterPriceLevel: 'مستوى السعر',
  compoundsFilterConstruction: 'حالة الإنشاء',
  compoundsFilterFinishing: 'نوع التشطيب',
  compoundsFilterPayment: 'طرق السداد',
  compoundsOpenFilters: 'تصفية النتائج',
  compoundsEmptyTitle: 'لا توجد كمبوندات مطابقة',
  compoundsEmptyDescription:
    'جرّب تعديل الفلاتر أو اختيار موقع آخر لعرض مشاريع متاحة.',
  compoundsEmptyReset: 'إعادة ضبط الفلاتر',
  compoundsProjectsCount: 'مشروع',
  compoundsStartsFrom: 'يبدأ من',
  compoundsPromoTitle: 'أعلن عن مشروعك العقاري',
  compoundsPromoBody: 'اعرض كمبوندك أمام آلاف الباحثين عن وحدات سكنية جديدة.',
  compoundsPromoCta: 'تواصل معنا',
  compoundsCallShort: 'اتصل',
  compoundDetailsPlaceholderTitle: 'صفحة تفاصيل الكمبوند',
  compoundDetailsPlaceholderBody:
    'تفاصيل هذا المشروع قيد التجهيز وستكون متاحة قريبًا.',

  // Compound details
  compoundDetailsBreadcrumbCompounds: 'كمبوندات',
  compoundDetailsCategory: 'كمبوند',
  compoundDetailsShare: 'نشر',
  compoundDetailsBrochure: 'بروشور',
  compoundDetailsRecommendation: 'التوصية',
  compoundDetailsProBadge: 'Pro',
  compoundDetailsUnitsTitle: 'وحدات الكمبوند',
  compoundDetailsUnitsDeveloper: 'للبيع - المطور',
  compoundDetailsUnitsResale: 'للبيع - معلنين',
  compoundDetailsUnitsAdvertiserSale: 'للبيع - معلنين',
  compoundDetailsUnitsAdvertiserRent: 'للإيجار - معلنين',
  compoundDetailsUnitsMore: 'المزيد',
  compoundDetailsContentTitle: 'تفاصيل الكمبوند',
  compoundDetailsMapTitle: 'الموقع على الخريطة',
  compoundDetailsShowLocation: 'اعرض الموقع',
  compoundDetailsDeveloperTitle: 'المطور',
  compoundDetailsDeveloperMemberSince: 'عضو منذ',
  compoundDetailsDeveloperProjects: 'مشروع',
  compoundDetailsDeveloperForSale: 'للبيع',
  compoundDetailsDeveloperForRent: 'للإيجار',
  compoundDetailsDeveloperView: 'عرض المطور',
  compoundDetailsFaqTitle: 'الأسئلة الشائعة',
  compoundDetailsGuideTitle: 'دليل الكمبوندات',
  compoundDetailsGuideBody:
    'استكشف المشاريع وقارن الوحدات والأسعار في مكان واحد قبل اتخاذ قرار الشراء.',
  compoundDetailsVerified: 'موثق',
} as const;
